from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class AcousticDescriptorPayload:
    """
    Text-mediated acoustic features and numerical OCEAN scores mapped from a synchronized audio segment.

    Attributes:
        segment_id (int): Sequence identifier linking back to the source synchronized segment.
        start_time_sec (float): Absolute start time of the acoustic slice.
        end_time_sec (float): Absolute end time of the acoustic slice.
        vocal_cues (Tuple[str, ...]): Discrete natural language descriptors generated by the pipeline.
        extraversion_score (float): Raw extraversion probability.
        neuroticism_score (float): Raw neuroticism probability.
        agreeableness_score (float): Raw agreeableness probability.
        conscientiousness_score (float): Raw conscientiousness probability.
        openness_score (float): Raw openness probability.
    """
    segment_id: int
    start_time_sec: float
    end_time_sec: float
    vocal_cues: Tuple[str, ...]
    extraversion_score: float
    neuroticism_score: float
    agreeableness_score: float
    conscientiousness_score: float
    openness_score: float

    def __post_init__(self) -> None:
        """
        Validates structural integrity, temporal boundaries, and score types.

        Raises:
            TypeError: If types for identifiers, tuple components, or scores are violated.
            ValueError: If temporal boundaries are inverted, negative, or cues are empty.
        """
        if not isinstance(self.segment_id, int) or self.segment_id < 0:
            raise ValueError("segment_id must be a non-negative integer.")
        
        if not isinstance(self.start_time_sec, (int, float)) or self.start_time_sec < 0.0:
            raise ValueError("start_time_sec must be non-negative.")
        
        if not isinstance(self.end_time_sec, (int, float)):
            raise TypeError("end_time_sec must be a float.")
        
        if self.end_time_sec <= self.start_time_sec:
            raise ValueError("end_time_sec must be strictly greater than start_time_sec.")
        
        if not isinstance(self.vocal_cues, tuple):
            raise TypeError("vocal_cues must be a tuple of strings.")
        
        for cue in self.vocal_cues:
            if not isinstance(cue, str):
                raise TypeError("Each vocal cue must be a string.")
            if not cue.strip():
                raise ValueError("Vocal cues cannot be empty strings.")

        scores: Tuple[float, ...] = (
            self.extraversion_score,
            self.neuroticism_score,
            self.agreeableness_score,
            self.conscientiousness_score,
            self.openness_score
        )
        
        for score in scores:
            if not isinstance(score, (int, float)):
                raise TypeError("OCEAN scores must be numerical values.")