from dataclasses import dataclass


@dataclass(frozen=True)
class CoachingFeedbackPayload:
    """
    The final egress payload containing the LLM-generated coaching feedback.

    Attributes:
        segment_id (int): Sequence identifier linking back to the source synchronized segment.
        feedback_text (str): The structured markdown feedback generated by the LLM.
    """
    segment_id: int
    feedback_text: str

    def __post_init__(self) -> None:
        """
        Validates structural integrity of the final output.

        Raises:
            TypeError: If types for identifiers or text are violated.
            ValueError: If the identifier is negative or the text is empty.
        """
        if not isinstance(self.segment_id, int) or isinstance(self.segment_id, bool):
            raise TypeError("segment_id must be a strictly typed integer.")
        if self.segment_id < 0:
            raise ValueError("segment_id must be a non-negative integer.")

        if not isinstance(self.feedback_text, str):
            raise TypeError("feedback_text must be a string.")
        if not self.feedback_text.strip():
            raise ValueError("feedback_text cannot be empty or whitespace.")