/**
 * Represents the exhaustive states of the frontend WebSocket and recording lifecycle.
 */
export type ConnectionState =
  | "IDLE"
  | "CONNECTING"
  | "CONNECTED"
  | "RECORDING"
  | "PROCESSING"
  | "EVALUATION_READY"
  | "ERROR";

/**
 * Represents the five continuous factors of the OCEAN personality model.
 * Keys are snake_cased to strictly match the Python backend JSON serialization.
 */
export interface OceanScores {
  /** Raw extraversion probability score bounded between 0.0 and 1.0. */
  extraversion_score: number;
  /** Raw neuroticism probability score bounded between 0.0 and 1.0. */
  neuroticism_score: number;
  /** Raw agreeableness probability score bounded between 0.0 and 1.0. */
  agreeableness_score: number;
  /** Raw conscientiousness probability score bounded between 0.0 and 1.0. */
  conscientiousness_score: number;
  /** Raw openness probability score bounded between 0.0 and 1.0. */
  openness_score: number;
}

/**
 * Text-mediated acoustic features and numerical OCEAN scores mapped from a synchronized audio segment.
 */
export interface AcousticDescriptorPayload extends OceanScores {
  /** Sequence identifier linking back to the source synchronized segment. */
  segment_id: number;
  /** Absolute start time of the acoustic slice in seconds. */
  start_time_sec: number;
  /** Absolute end time of the acoustic slice in seconds. */
  end_time_sec: number;
  /** Discrete natural language descriptors generated by the acoustic pipeline. */
  vocal_cues: string[];
}

/**
 * Structured feedback payload generated by the downstream LLM judge.
 */
export interface CoachingFeedbackPayload {
  /** Sequence identifier linking back to the evaluated segment. */
  segment_id: number;
  /** Markdown-formatted text containing the Present-Past-Future evaluation. */
  feedback_text: string;
}

/**
 * Represents the real-time processing status of the multimodal fusion nexus.
 */
export interface PipelineModalityStatus {
  /** Sequence identifier for the active sliding window. */
  segment_id: number;
  /** Indicates if the transcription and semantic extraction completed. */
  semantic: boolean;
  /** Indicates if the vocal cue and OCEAN trait extraction completed. */
  acoustic: boolean;
  /** Indicates if the visual gaze and micro-expression extraction completed. */
  facial: boolean;
  /** Indicates if the skeletal posture and gesture extraction completed. */
  skeletal: boolean;
}

/**
 * Discriminated union of all possible incoming WebSocket payloads from the GCP backend.
 * Provides type safety for routing incoming network frames to appropriate reducers.
 */
export type BackendIncomingMessage =
  | { type: "modality_status"; payload: PipelineModalityStatus }
  | { type: "coaching_feedback"; payload: CoachingFeedbackPayload }
  | { type: "acoustic_telemetry"; payload: AcousticDescriptorPayload }
  | { type: "terminal_error"; error: string };