"use client";

import type { ReactElement } from "react";
import ReactMarkdown from "react-markdown";
import { FileQuestion } from "lucide-react";

export interface LLMMarkdownProps {
  /** The raw Markdown string generated by the AI judge. */
  content: string | undefined | null;
  /** Optional Tailwind class string for container styling injection. */
  className?: string;
}

/**
 * Parses and securely renders Markdown text into a high-tech, glassmorphic UI container.
 * Employs custom component mapping to inject strict Tailwind typography rules.
 *
 * @param {LLMMarkdownProps} props - The raw Markdown content and layout attributes.
 * @returns {ReactElement} The styled evaluation read-out or a fallback error state.
 */
export function LLMMarkdown({
  content,
  className = "",
}: LLMMarkdownProps): ReactElement {
  if (!content || content.trim().length === 0) {
    return (
      <div
        className={`flex h-64 w-full flex-col items-center justify-center rounded-2xl border border-white/5 bg-neutral-950/50 p-6 text-center shadow-inner backdrop-blur-sm ${className}`}
      >
        <FileQuestion className="mb-4 h-12 w-12 text-neutral-600" strokeWidth={1} />
        <span className="font-mono text-sm tracking-widest text-neutral-500 uppercase">
          Evaluation Data Unavailable
        </span>
      </div>
    );
  }

  return (
    <div
      className={`relative overflow-hidden rounded-2xl border border-white/10 bg-black/60 p-8 shadow-[0_0_50px_rgba(34,211,238,0.05)] backdrop-blur-xl ring-1 ring-white/5 ${className}`}
    >
      <div className="pointer-events-none absolute left-0 top-0 h-full w-1 bg-gradient-to-b from-cyan-500 via-emerald-500 to-transparent opacity-50" />
      
      <div className="prose prose-invert max-w-none">
        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h1 className="mb-6 font-mono text-2xl font-bold tracking-tight text-white">
                {children}
              </h1>
            ),
            h2: ({ children }) => (
              <h2 className="mb-4 mt-8 font-mono text-xl font-semibold tracking-wide text-cyan-400">
                {children}
              </h2>
            ),
            h3: ({ children }) => (
              <h3 className="mb-3 mt-6 font-mono text-sm uppercase tracking-widest text-emerald-400">
                {children}
              </h3>
            ),
            p: ({ children }) => (
              <p className="mb-4 leading-relaxed text-neutral-300">
                {children}
              </p>
            ),
            strong: ({ children }) => (
              <strong className="font-semibold text-white drop-shadow-[0_0_8px_rgba(255,255,255,0.3)]">
                {children}
              </strong>
            ),
            ul: ({ children }) => (
              <ul className="mb-6 ml-4 list-none space-y-2">{children}</ul>
            ),
            li: ({ children }) => (
              <li className="relative pl-6 text-neutral-300 before:absolute before:left-0 before:top-2.5 before:h-1.5 before:w-1.5 before:rounded-full before:bg-cyan-500/50">
                {children}
              </li>
            ),
          }}
        >
          {content}
        </ReactMarkdown>
      </div>
    </div>
  );
}