import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Tuple, Iterator
from itertools import islice

import jiwer
import pandas as pd
from omegaconf import open_dict
import nemo.collections.asr as nemo_asr
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
from contextlib import nullcontext

import torch

from src.core.registry import register_domain

logger = logging.getLogger(__name__)


def load_nemo_model(architecture: str, device: torch.device) -> Any:
    """
    Initializes a NeMo ASR model and configures precision mapping for the target compute device.

    Args:
        architecture (str): The specific model architecture identifier.
        device (torch.device): The target PyTorch hardware device.

    Returns:
        Any: The loaded and precision-configured NeMo model instance.
    """
    arch_lower: str = architecture.lower()
    
    if "canary" in arch_lower:
        model_id: str = "nvidia/canary-1b-v2"
        model: Any = nemo_asr.models.EncDecMultiTaskModel.from_pretrained(
            model_name=model_id, 
            map_location=device
        )
    else:
        model_mapping: Dict[str, str] = {
            "parakeet-tdt-0.6b-v3": "nvidia/parakeet-tdt-0.6b-v3",
        }
        model_id = model_mapping.get(arch_lower, f"nvidia/{arch_lower}")
        model = nemo_asr.models.ASRModel.from_pretrained(
            model_name=model_id, 
            map_location=torch.device('cpu')  # Fix applied only to Parakeet
        )
    
    if device.type == "cuda":
        model = model.half()
        
        if hasattr(model, 'preprocessor') and isinstance(model.preprocessor, torch.nn.Module):
            model.preprocessor = model.preprocessor.float()
            
        if hasattr(model, 'joint') and isinstance(model.joint, torch.nn.Module):
            model.joint = model.joint.float()
            
        if hasattr(model, 'decoder') and isinstance(model.decoder, torch.nn.Module):
            model.decoder = model.decoder.float()
            
        if hasattr(model, 'cfg') and hasattr(model.cfg, 'decoding'):
            with open_dict(model.cfg.decoding):
                model.cfg.decoding.cuda_graphs = False
            model.change_decoding_strategy(model.cfg.decoding)
    else:
        model = model.float()

    return model.to(device)


def load_huggingface_model(architecture: str, device: torch.device) -> Any:
    """
    Instantiates a Hugging Face ASR pipeline with optimized precision.

    Args:
        architecture (str): The Hugging Face model architecture identifier.
        device (torch.device): The target PyTorch hardware device.

    Returns:
        Any: The configured Hugging Face AutomaticSpeechRecognitionPipeline.
    """
    model_mapping: Dict[str, str] = {
        "whisper-large-v3": "openai/whisper-large-v3",
    }
    model_id: str = model_mapping.get(architecture.lower(), f"openai/{architecture.lower()}")
    dtype: torch.dtype = torch.float16 if device.type == "cuda" else torch.float32
    
    logger.info("Loading Hugging Face model checkpoint: %s with dtype: %s on %s", model_id, dtype, device)

    model = AutoModelForSpeechSeq2Seq.from_pretrained(
        model_id, 
        torch_dtype=dtype, 
        low_cpu_mem_usage=True
    ).to(device)

    processor = AutoProcessor.from_pretrained(model_id)

    return pipeline(
        "automatic-speech-recognition",
        model=model,
        tokenizer=processor.tokenizer,
        feature_extractor=processor.feature_extractor,
        torch_dtype=dtype,
        device=device,
        return_timestamps=True,
    )


def initialize_transcription_model(config: Dict[str, Any], device: torch.device) -> Tuple[Any, str]:
    """
    Routes model initialization based on the configured framework.

    Args:
        config (Dict[str, Any]): The configuration dictionary containing model metadata.
        device (torch.device): The PyTorch hardware device.

    Returns:
        Tuple[Any, str]: A tuple comprising the model instance and the framework identifier string.
    """
    architecture: str = config.get("architecture", "Parakeet-TDT-0.6B-v3")
    framework: str = config.get("framework", "nemo").lower()

    if framework == "nemo":
        return load_nemo_model(architecture, device), framework
    return load_huggingface_model(architecture, device), framework


def calculate_wer_preserving_disfluencies(predictions: List[str], references: List[str]) -> float:
    """
    Computes the Word Error Rate (WER) while preserving disfluency markers by bypassing standard normalization.

    Args:
        predictions (List[str]): Hypothesis transcriptions generated by the model.
        references (List[str]): Ground truth transcriptions.

    Returns:
        float: The calculated Word Error Rate.
    """
    transformation = jiwer.Compose([
        jiwer.ToLowerCase(),
        jiwer.RemoveMultipleSpaces(),
        jiwer.Strip(),
        jiwer.RemovePunctuation(),
        jiwer.ReduceToListOfListOfWords(),
    ])

    return float(
        jiwer.wer(
            reference=references,
            hypothesis=predictions,
            reference_transform=transformation,
            hypothesis_transform=transformation,
        )
    )


def _chunk_iterable(iterable: List[str], size: int) -> Iterator[List[str]]:
    """
    Yields bounded sequential subsets from an iterable.

    Args:
        iterable (List[str]): The source sequence to partition.
        size (int): The maximum length of each generated subset.

    Yields:
        Iterator[List[str]]: A generator producing partitioned subsets.
    """
    iterator = iter(iterable)
    for first in iterator:
        yield [first] + list(islice(iterator, size - 1))


def _extract_text(result: Any) -> str:
    """
    Safely resolves the string transcription from heterogeneous framework output objects.

    Args:
        result (Any): The raw output representation from the inference model.

    Returns:
        str: The extracted plain text transcription.
    """
    if result is None:
        return ""
    if isinstance(result, tuple):
        result = result[0]
    if hasattr(result, "text"):
        return str(result.text)
    return str(result)


def load_checkpoint_map(checkpoint_path: Path) -> Dict[str, str]:
    """
    Reads existing transcription results from persistent storage to enable process resumption.

    Args:
        checkpoint_path (Path): The designated file path for the state map.

    Returns:
        Dict[str, str]: A mapping of audio file paths to their corresponding transcriptions.
    """
    if checkpoint_path.exists():
        try:
            with open(checkpoint_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                logger.info("Resuming from checkpoint. Found %d existing transcriptions at %s", len(data), checkpoint_path)
                return data
        except json.JSONDecodeError as e:
            logger.error("Checkpoint file is corrupted. Starting fresh. Error: %s", e)
    return {}


def save_checkpoint_map(checkpoint_map: Dict[str, str], checkpoint_path: Path) -> None:
    """
    Executes an atomic write operation to persist the transcription state map.

    Args:
        checkpoint_map (Dict[str, str]): The current state mapping of paths to transcriptions.
        checkpoint_path (Path): The target destination file path.
    """
    checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
    temp_path: Path = checkpoint_path.with_suffix('.tmp')
    
    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(checkpoint_map, f, indent=2, ensure_ascii=False)
        
    temp_path.replace(checkpoint_path)


def _verify_audio_paths(paths: List[str]) -> List[str]:
    """
    Validates file existence for a batch of audio paths.

    Args:
        paths (List[str]): A list of file system paths to verify.

    Returns:
        List[str]: A filtered list containing only confirmed existing paths.
    """
    valid_paths: List[str] = []
    for p in paths:
        if Path(p).exists():
            valid_paths.append(p)
        else:
            logger.warning("Audio file not found on disk: %s", p)
    return valid_paths


def transcribe_batch(
    audio_paths: List[str],
    model: Any,
    framework: str,
    device: torch.device,
    batch_size: int = 4,
    checkpoint_path: Path = Path("src/results/checkpoints/transcription_checkpoint.json"),
    chunk_save_frequency: int = 20,
) -> List[str]:
    """
    Executes a resilient batch inference pipeline with atomic checkpointing and exception masking.
    Dynamically adjusts precision contexts based on hardware capabilities.

    Args:
        audio_paths (List[str]): The complete sequence of audio files targeted for transcription.
        model (Any): The initialized foundation model or pipeline.
        framework (str): The string identifier of the model framework.
        device (torch.device): The target compute hardware device.
        batch_size (int, optional): The quantity of items processed simultaneously. Defaults to 4.
        checkpoint_path (Path, optional): The target path for state persistence.
        chunk_save_frequency (int, optional): The interval frequency for state flushing. Defaults to 20.

    Returns:
        List[str]: An ordered sequence of transcriptions corresponding positionally to the input paths.
    """
    checkpoint_map: Dict[str, str] = load_checkpoint_map(checkpoint_path)
    
    pending_paths: List[str] = [p for p in audio_paths if p not in checkpoint_map]
    logger.info(
        "Total samples: %d | Cached: %d | Pending transcription: %d",
        len(audio_paths), len(checkpoint_map), len(pending_paths)
    )

    device_type: str = device.type
    
    # Avoid bfloat16 on CPU as older processors (OneDNN) lack primitive support
    inference_context = torch.autocast(device_type="cuda", dtype=torch.float16) if device_type == "cuda" else nullcontext()

    if pending_paths:
        for chunk in _chunk_iterable(pending_paths, chunk_save_frequency):
            valid_chunk = _verify_audio_paths(chunk)
            
            if not valid_chunk:
                for p in chunk:
                    checkpoint_map[p] = "[ERROR: FILE_NOT_FOUND]"
                continue

            try:
                if framework == "nemo":
                    with torch.no_grad(), inference_context:
                        chunk_results: Any = model.transcribe(
                            valid_chunk, 
                            batch_size=batch_size, 
                            num_workers=0,
                            use_lhotse=False
                        )
                    
                    if isinstance(chunk_results, tuple):
                        chunk_results = chunk_results[0]
                        
                    if isinstance(chunk_results, list):
                        extracted_texts = list(map(_extract_text, chunk_results))
                        for audio_p, text in zip(valid_chunk, extracted_texts):
                            checkpoint_map[audio_p] = text
                        
                else: 
                    with torch.no_grad(), inference_context:
                        chunk_results = model(
                            valid_chunk, 
                            batch_size=batch_size, 
                            generate_kwargs={"task": "transcribe", "language": "en"}
                        )
                    
                    extracted_texts = [str(r["text"]) for r in chunk_results]
                    for audio_p, text in zip(valid_chunk, extracted_texts):
                        checkpoint_map[audio_p] = text

            except RuntimeError as e:
                logger.error("Runtime Error processing chunk: %s", e)
                for p in valid_chunk:
                    checkpoint_map[p] = f"[ERROR: {str(e)[:50]}]"
            except Exception as e:
                logger.error("Unexpected error processing chunk: %s", e)
                for p in valid_chunk:
                    checkpoint_map[p] = "[ERROR: UNEXPECTED_FAILURE]"
            
            save_checkpoint_map(checkpoint_map, checkpoint_path)
            logger.info("Saved progress: %d/%d processed", len(checkpoint_map), len(audio_paths))
            
            if device_type == "cuda":
                torch.cuda.synchronize()
                # torch.cuda.empty_cache()

            # if "parakeet" in str(checkpoint_path).lower():
            #     logger.info("Parakeet chunk complete. Exiting cleanly to flush C++ allocator...")
            #     sys.exit(0)

    return [checkpoint_map.get(p, "[ERROR: UNPROCESSED]") for p in audio_paths]


def compute_stratified_metrics(results_df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculates segmented error metrics aggregated by signal-to-noise ratio classifications.
    Gracefully handles empty dataframes or missing columns to prevent pipeline crashes.

    Args:
        results_df (pd.DataFrame): The compiled dataset containing predictions and reference metrics.

    Returns:
        pd.DataFrame: A structured summary of error rates distributed across environmental groupings.
    """
    metrics_summary: List[Dict[str, Any]] = []
    
    # Filter out errors to isolate valid transcriptions
    valid_df = results_df[~results_df['prediction'].str.startswith("[ERROR", na=False)]

    if valid_df.empty:
        logger.warning("No valid transcriptions available for stratified metrics computation.")
        return pd.DataFrame(columns=["target_snr_db", "sample_count", "wer"])

    if "target_snr_db" not in valid_df.columns:
        logger.warning("Column 'target_snr_db' absent from manifest. Bypassing stratification.")
        return pd.DataFrame(columns=["target_snr_db", "sample_count", "wer"])

    for snr_val, group in valid_df.groupby("target_snr_db"):
        wer: float = calculate_wer_preserving_disfluencies(
            predictions=group["prediction"].tolist(),
            references=group["ground_truth_transcript"].tolist(),
        )
        metrics_summary.append({
            "target_snr_db": snr_val,
            "sample_count": len(group),
            "wer": wer,
        })

    return pd.DataFrame(metrics_summary).sort_values(by="target_snr_db", ascending=False)


def resolve_device(config_device: str, global_device: torch.device) -> torch.device:
    """
    Determines the appropriate execution hardware device based on configuration and availability.

    Args:
        config_device (str): The device identifier string derived from configuration files.
        global_device (torch.device): The fallback device identifier established by CLI parameters.

    Returns:
        torch.device: The resolved PyTorch hardware device object.
    """
    if config_device in ["cuda", "cpu"]:
        resolved = torch.device(config_device)
        if config_device == "cuda" and not torch.cuda.is_available():
            logger.warning("CUDA requested in config but unavailable on hardware. Falling back to CPU.")
            return torch.device("cpu")
        return resolved
    return global_device


@register_domain("transcription")
def run_transcription_experiment(config: Dict[str, Any], global_device: torch.device) -> None:
    """
    Orchestrates the end-to-end execution of the primary ASR evaluation pipeline.

    Args:
        config (Dict[str, Any]): The hierarchical dictionary containing experiment constraints.
        global_device (torch.device): The globally scoped default hardware target.

    Raises:
        FileNotFoundError: Triggered when the defined benchmark manifest cannot be located.
    """
    device: torch.device = resolve_device(config.get("device", "").lower(), global_device)
    logger.info("Running transcription experiment on target device: %s", device)

    model_config: Dict[str, Any] = config.get("model_config", {})
    data_config: Dict[str, Any] = config.get("data_config", {})
    eval_config: Dict[str, Any] = config.get("evaluation", {})

    manifest_path = Path(data_config.get("manifest_path", "src/data/transcription/benchmark_disfluency/benchmark_manifest.csv"))
    if not manifest_path.exists():
        logger.error("Benchmark manifest not found: %s", manifest_path)
        raise FileNotFoundError(f"Manifest file not found at: {manifest_path}")

    manifest_df: pd.DataFrame = pd.read_csv(manifest_path)
    logger.info("Loaded %d manifest records for evaluation", len(manifest_df))

    model, framework = initialize_transcription_model(model_config, device)

    batch_size: int = int(data_config.get("batch_size", 4))
    chunk_save_freq: int = int(data_config.get("chunk_save_frequency", 20))
    
    arch_name: str = model_config.get("architecture", "model").replace("/", "_")
    default_ckpt: str = f"src/results/transcription/checkpoints/{arch_name}_checkpoint.json"
    checkpoint_file = Path(eval_config.get("checkpoint_path", default_ckpt))
    
    audio_paths: List[str] = manifest_df["audio_path"].tolist()

    predictions: List[str] = transcribe_batch(
        audio_paths=audio_paths,
        model=model,
        framework=framework,
        device=device,
        batch_size=batch_size,
        checkpoint_path=checkpoint_file,
        chunk_save_frequency=chunk_save_freq,
    )
    
    manifest_df["prediction"] = predictions
    valid_manifest = manifest_df[~manifest_df['prediction'].str.startswith("[ERROR", na=False)]
    
    overall_wer: float = 0.0
    if not valid_manifest.empty:
        overall_wer = calculate_wer_preserving_disfluencies(
            predictions=valid_manifest["prediction"].tolist(),
            references=valid_manifest["ground_truth_transcript"].tolist(),
        )

    stratified_summary: pd.DataFrame = compute_stratified_metrics(manifest_df)

    output_path = Path(eval_config.get("output_results_path", f"src/results/transcription/{arch_name}_results.csv"))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_df.to_csv(output_path, index=False)
    
    metrics_path = output_path.with_name(f"{output_path.stem}_metrics.json")
    metrics_data = {
        "model_architecture": model_config.get("architecture"),
        "framework": framework,
        "total_samples": len(manifest_df),
        "valid_samples": len(valid_manifest),
        "overall_wer": overall_wer,
        "stratified_wer": stratified_summary.to_dict(orient="records")
    }
    
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(metrics_data, f, indent=4)

    logger.info("Architecture: %s | Framework: %s", model_config.get("architecture"), framework)
    logger.info("Valid Transcriptions: %d / %d", len(valid_manifest), len(manifest_df))
    logger.info("Overall Disfluency-Preserving WER: %.4f", overall_wer)
    logger.info("Stratified Metrics:\n%s", stratified_summary.to_string(index=False))
    logger.info("Results successfully saved to: %s", output_path)
    logger.info("Metrics successfully saved to: %s", metrics_path)